name: Frontend CI - CD

on:
  push:
    branches:
      - main
      - master
      - dev*
      - staging
    tags:
      - 'v*'
    paths:
      - 'practice/month2/week1/front-end/**'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'practice/month2/week1/front-end/**'

env:
  NODE_VERSION: '24'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  #  REGISTRY: docker.io
  #  IMAGE_NAME: nguyenhoanghai/devops-roadmap # For dockerhub
  FRONTEND_DIR: practice/month2/week1/front-end

jobs:
  # ============================================================================
  # JOB 1: Code Quality & Testing
  # ============================================================================
  test:
    name: Test front-end
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }}

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v6

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: '${{ env.FRONTEND_DIR }}/yarn.lock'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Run tests
      - name: Run test
        run: yarn test

  # ============================================================================
  # JOB 2: Build Application
  # ============================================================================
  build:
    name: Build application
    runs-on: ubuntu-latest
    needs: test

    defaults:
      run:
        working-directory: ${{ env.FRONTEND_DIR }}

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v6

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: yarn
          cache-dependency-path: '${{ env.FRONTEND_DIR }}/yarn.lock'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Build application
      - name: Build application
        run: yarn build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      # Step 5: Upload to artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v6
        with:
          name: frontend-dist
          path: ${{ env.FRONTEND_DIR }}/dist/
          retention-days: 7

  # ============================================================================
  # JOB 3: Build Docker Image
  # ============================================================================
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name != 'pull_request'

    permissions:
      contents: read
      packages: write  # Only use with ghrc

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 2: Setup Docker Buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      # Step 3: Login docker
      - name: Login to github container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Extract metadata
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            # Tag: latest (cho main branch)
            type=raw,value=latest,enable={{is_default_branch}}
            
            # Tag: v1.0.0 (từ git tag)
            type=semver,pattern={{version}}           # v1.0.0
            type=semver,pattern={{major}}.{{minor}}   # v1.0
            type=semver,pattern={{major}}             # v1
            
            # Tag: main-sha123abc (branch + commit)
            type=sha,prefix={{branch}}-,format=short
            
            # Tag: staging (từ branch name)
            type=ref,event=branch
            
            # Tag: pr-123 (từ PR number)
            type=ref,event=pr
            
            # Environment tags
            type=raw,value=production,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=staging,enable=${{ github.ref == 'refs/heads/staging' }}
            type=raw,value=development,enable=${{ github.ref == 'refs/heads/develop' }}

      # Step 5: Build and push
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          context: ${{ env.FRONTEND_DIR }}
          file: ${{ env.FRONTEND_DIR }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
